### ISSUE TITLE
unknown command "oidc-login" for "kubectl"

### ISSUE THREAD

**Issue by clbarrett** [int128/kubelogin#1039]
## Describe the issue
I have a new computer and am trying to get kubectl working on Windows 11.  Installed Kubectl, signed into my AKS server and got the kube login error.  Did a Chocolaty install kubelogin, rebooted my git bash terminal and ran kubectl oidc-login setup.  But kubectl is not recognizing oidc-login.

## To reproduce
Run the following command in a git bash terminal
kubectl oidc-login / kubectl oidc-login setup

## Your environment
- OS: Windows 11
- Terminal:  Git Bash
- kubelogin 1.28.0
- kubectl version: e.g. v1.29.1
- OpenID Connect provider: NA

**Comment by j-q-in-berlin** [comment]
Same here. Any ideas?

**Comment by clbarrett** [comment]
@j-q-in-berlin Here's what I found works:
kubelogin convert-kubeconfig -l azurecli

Weirdly though this has to be done every time after running az aks get-credentials.  Which I ended up having to incorporate into my build pipelines as I'm using self-hosted build agents.

**Comment by j-q-in-berlin** [comment]
Thank you!

**Comment by clbarrett** [comment]
Glad it helped.  

I'm going to close this issue as I did have it resolved.  I will note that it is very odd that I have to continuously run the kubelogin convert-kubeconfig -l azurecli every time I get the aks credentials.  My build agents support multiple AKS clusters and it is slightly awkward to have to convert every time.
