### ISSUE TITLE
groups not present in ID Token when using GitLab

### ISSUE THREAD

**Issue by lucj** [int128/kubelogin#1129]
Hi, I'm trying to use kubelogin with GitLab IDP.  When I use the following command, I get an ID Token but there is no groups property in that one, only groups_direct.

```
kubectl oidc-login setup --oidc-issuer-url=https://gitlab.com --oidc-client-id=$CLIENT_ID --oidc-client-secret=$CLIENT_SECRET
```

groups_direct is the list of group a user is a direct member of, whereas groups is the list of groups a user is member of either directly or via inheritance. As describe in GitLab [doc](https://docs.gitlab.com/ee/integration/openid_connect_provider.html), groups is not in the ID Token but in the userinfo.

Any idea of the syntax I should use to claim the groups ?
Does this involve --oidc-extra-scope or --oidc-groups-claim parameters ? (I tested --oidc-extra-scope with groups, userinfo/groups, ... but it doesn't work)

**Comment by ma44in** [comment]
I'm facing the same issue. @lucj could you find a solution?

**Comment by lucj** [comment]
Hello @ma44in, I think I was missing a scope. I detailed the configuration in this [article](https://www.exoscale.com/syslog/exoscale-sks-oidc-gitlab/), I hope this can help.
