### ISSUE TITLE
groups claim not work.

### ISSUE THREAD

**Issue by zwwhdls** [int128/kubelogin#114]
Hi guys,

I tried kubelogin for my kube cluster with keycloak, but I have encountered some problems. 

I setup keycloak client as follows:
![image](https://user-images.githubusercontent.com/33822635/61612678-cf51f100-ac91-11e9-8c12-03398022ab91.png)

Then I assigned the user "test" with "admin" role in "kubernetes" client, which is as follows:
![image](https://user-images.githubusercontent.com/33822635/61612812-248e0280-ac92-11e9-9a63-c4038d08ed08.png)

Then I tried login with test, get a JWT with the claim:

```
echo eyJqdGkiOiI5YTM4OTUwZi0xODE3LTQxNGItYmM3MS00MGMzOTU2ZWYzYTEiLCJleHAiOjE1NjM3Nzg2OTEsIm5iZiI6MCwiaWF0IjoxNTYzNzc4MzkxLCJpc3MiOiJodHRwczovLzE3Mi4xNi4xMDUuMTo4MDgyL2F1dGgvcmVhbG1zL2hkbHMiLCJhdWQiOiJrdWJlcm5ldGVzIiwic3ViIjoiZTExZmQ1ODYtZTNiYS00YmNlLWFkOWQtM2E4MjZjNmRiYTk1IiwidHlwIjoiSUQiLCJhenAiOiJrdWJlcm5ldGVzIiwiYXV0aF90aW1lIjowLCJzZXNzaW9uX3N0YXRlIjoiY2UxZmRmOWYtYzNlNS00MWE1LWE3MjUtZmE3NDdiNDVjZDdlIiwiYWNyIjoiMSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZ3JvdXBzIjoiW2t1YmVybmV0ZXM6YWRtaW5dIiwicHJlZmVycmVkX3VzZXJuYW1lIjoidGVzdCJ9|base64 -D
{"jti":"9a38950f-1817-414b-bc71-40c3956ef3a1","exp":1563778691,"nbf":0,"iat":1563778391,"iss":"https://172.16.105.1:8082/auth/realms/hdls","aud":"kubernetes","sub":"e11fd586-e3ba-4bce-ad9d-3a826c6dba95","typ":"ID","azp":"kubernetes","auth_time":0,"session_state":"ce1fdf9f-c3e5-41a5-a725-fa747b45cd7e","acr":"1","email_verified":false,"groups":"[kubernetes:admin]","preferred_username":"test"}
```

But when I use `kubectl get po` , I got the error:

```
# kubectl  get po
Error from server (Forbidden): pods is forbidden: User "test" cannot list resource "pods" in API group "" in the namespace "default"
```

My apiserver settings are:

```
    - --oidc-issuer-url=https://172.16.105.1:8082/auth/realms/hdls
    - --oidc-client-id=kubernetes
    - --oidc-username-claim=preferred_username
    - --oidc-username-prefix=-
    - --oidc-groups-claim=["groups"]
    - --oidc-groups-prefix=-
```

ClusterRolebinding :
```
$ kubectl get clusterrolebinding keycloak-admin-group -oyaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRoleBinding","metadata":{"annotations":{},"name":"keycloak-admin-group"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"ClusterRole","name":"cluster-admin"},"subjects":[{"kind":"Group","name":"manager"},{"kind":"Group","name":"kubernetes:admin"},{"kind":"User","name":"hdls"}]}
  creationTimestamp: "2019-07-16T08:12:17Z"
  name: keycloak-admin-group
  resourceVersion: "4536867"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterrolebindings/keycloak-admin-group
  uid: 6d2eb87e-a7a1-11e9-9539-005056b40224
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: kubernetes:admin
```

My kubernetes version:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-26T00:04:52Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

I wanna know what's wrong with my operation or did I miss something?

Thankyou!

**Comment by int128** [comment]
It seems the `groups` claim of ID token is a string but it must be a list of strings (https://github.com/kubernetes/kubernetes/issues/33290). I think the following configuration may fix this issue.

- In your Keycloak, set the multivalued option to true.
- In your apiserver args, set `--oidc-groups-claim=groups`.

Good luck!

**Comment by zwwhdls** [comment]
@int128 Hi, thank you for your reply.

I set the configuration as follows:

1. In my Keycloak:
![image](https://user-images.githubusercontent.com/33822635/61626517-12bb5800-acb0-11e9-820a-b9672be05454.png)

2. In my apiserver args:
```
    - --oidc-client-id=kubernetes
    - --oidc-username-claim=preferred_username
    - --oidc-username-prefix=-
    - --oidc-groups-claim=groups
    - --oidc-groups-prefix=-
```

However, the problem is still there:

```
# kubectl get po
Error from server (Forbidden): pods is forbidden: User "test" cannot list resource "pods" in API group "" in the namespace "default"
```

**Comment by zwwhdls** [comment]
Sorry to disturb you ，I had made a mistake on my own foot. It works and I will close this issue.

**Comment by acukan** [comment]
@zwwhdls how did you resolve your problem?

**Comment by zwwhdls** [comment]
@acukan 
All configs of kubelogin and k8s apiserver are as this [doc](https://github.com/int128/kubelogin/blob/master/docs/keycloak.md) said. 
I add `apiGroup: rbac.authorization.k8s.io` in `ClusterRoleBinding.subjects.Group`

**Comment by grebois** [comment]
@zwwhdls Im also wondering how did you solve this problem, Im having one similar now https://github.com/int128/kubelogin/issues/250#issuecomment-662015539

**Comment by Bazze** [comment]
I've been struggling a lot with getting this to work, and today I finally found the issue. When you create the mapper to add the `groups` claim to the idToken, make sure to leave the "Client Role prefix" empty. The prefix is prepended by Kubernetes itself, so it should not be present on the group names in groups claim.

Example:
Let's say we have created an "admin" role in keycloak that we put into the groups claim and you have configured the kube-apiserver with `--oidc-groups-prefix=keycloak`, then the groups claim in your idToken should look like:
```json
{
  [...]
  "groups": ["admin"]
}
```

The role binding should then look like:
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: keycloak-admin-group
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: keycloak:admin
```

**Comment by C0rn3j** [comment]
I was struggling a bit with this in Keycloak 19+ and baremetal Kube, hope this helps someone.

![image](https://github.com/int128/kubelogin/assets/1641362/6787b0ec-931e-4236-8fa4-b0f14d6eb0d6)

Applied rbac.yaml:
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "nodes"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-binding
subjects:
  - kind: Group
    name: k8s
roleRef:
  kind: ClusterRole
  name: k8s
  apiGroup: rbac.authorization.k8s.io
```

/etc/kubernetes/manifests/kube-apiserver.yaml
```yaml
    - --oidc-issuer-url=https://auth.company.cz/auth/realms/company
    - --oidc-client-id=test-k8s
    - --oidc-username-claim=preferred_username
    - --oidc-groups-claim=groups
    - --oidc-ca-file=/etc/kubernetes/pki/keycloak-ca.crt
    - '--oidc-username-prefix=oidc:'
```

```bash
echo | openssl s_client -connect auth.company.cz:443 -servername auth.company.cz | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > /etc/kubernetes/pki/keycloak-ca.crt
```
