### ISSUE TITLE
authorization flow does not work if client-secret contains any special characters

### ISSUE THREAD

**Issue by i300543** [int128/kubelogin#115]
Hello, i have encountered an issue when using any special symbols in client-secret, e.g. 
! or +, the basic credentials generated by the authorization flow are invalid - it looks like base64 encoding issue:
when running the flow with -v=8
we see the following output:

13:07:50.619887 auth.go:93: Performing the authentication code flow
Open http://localhost:8000 for authentication
13:08:08.636807 transport.go:30: POST /oauth2/token HTTP/1.1
Host: <oidc.url>.com
User-Agent: Go-http-client/1.1
Content-Length: 110
Authorization: Basic VDAwMDAwMDpBYmNkMTIzNCUyMQ==
Content-Type: application/x-www-form-urlencoded
Accept-Encoding: gzip

code=d5cbdc32c366541c07732f27a43db1b0&grant_type=authorization_code&redirect_uri=http%3A%2F%2Flocalhost%3A8000
13:08:09.117823 transport.go:40: HTTP/1.1 401

the credentials used here are invalid:
 Basic VDAwMDAwMDpBYmNkMTIzNCUyMQ==
those are decoded to T000000:Abcd1234%21 instead of T000000:Abcd1234!
and because of that we get 401 response.

our kubeconfig looks like this:
...
users:
- name: shoot--devx-eldor--fsclientali
  user:
    auth-provider:
      config:
        client-id: T000000
        client-secret: Abcd1234!
        idp-issuer-url: https://<oidc.url>
      name: oidc

**Comment by int128** [comment]
Would you quote the client secret with double quotes? like:

```yaml
  client-secret: "Abcd1234!"
```

**Comment by int128** [comment]
Sorry, I could reproduce the issue. Quoting a secret in yaml does not take effect.

This seems expected behavior as https://github.com/golang/oauth2/issues/237.
