### ISSUE TITLE
PKCE authorization flow

### ISSUE THREAD

**Issue by bartse** [int128/kubelogin#146]
Hi,

Is there any plan to support the PKCE authorization code flow? From the specs it looks interesting but not sure this is a widely adopted flow?

I know this is not supported on all providers but having to share a client secret in your kubeconfig with fellow developers seems a bit cumbersome? Unless there is another way of doing this that I'm not aware off?

Currently I've integrated our Kubernetes API with Okta(authorization code using client secret) and this work perfectly.

**Comment by cmanzi** [comment]
@bartse Just curious, were you able to return the `groups` claim? I could not get that to work with this client.

**Comment by bartse** [comment]
Yes I was able to get the groups returned but only by specifying the full path to the okta authorization server(https://<custom-name>.okta.com/oauth2/default). This was worked out of the box on a developer account but doesn't work out of the box for a production account since this is a paid feature which needs to be enabled.

in classic UI:

Security > API > default > scopes
![image](https://user-images.githubusercontent.com/25744354/66034469-9479fe00-e509-11e9-818a-003e8460f6d3.png)

Next go to the Claims tab and add the groups claims as seen below
![image](https://user-images.githubusercontent.com/25744354/66034317-52e95300-e509-11e9-9eee-4711c0978a1d.png)

**Comment by int128** [comment]
Thank you for your contribution. I just created a developer account on Okta and will try the PKCE authorization flow.

**Comment by KKlapper** [comment]
I also like to avoid the distribution of the client-secret and would be happy to see the PKCE authorization code flow supported.

Could also the implicit flow help to prevent the client secret distribution? Is the implicit flow already supported?

**Comment by int128** [comment]
I created an implementation using the authorization code flow with PKCE and it works fine. Of course it does not need a client secret. I will release this feature soon.

**Comment by int128** [comment]
I just released v1.15.0 with this feature.
