### ISSUE TITLE
Manual mode : no  accces to http://localhost:8000

### ISSUE THREAD

**Issue by julien69740** [int128/kubelogin#148]
Hello everyone,

I have a kubernetes cluster on premise install on virtual machine linux Centos.

I want to use kubelogin to connect via our own OIDC provider.

I configure the apiserver to authorise oidc connexion.
I configure my kubeconfig with my informations about oidc connexion : client_id, issuer-url, client-secret.

It seems to works but when i use kubelogin on a virtual machine linux,  I have the following the message : open http://localhost:8000 for authentication

Unfornately, I can not access to localhost on my virtual machine and the vm doesnt have any browser.

I acces to my vm via mRemote and i would like to open a browser on my pc and not on the vm in localhost:8000.
I see  in the following tutorial : 

https://medium.com/@int128/kubectl-with-openid-connect-43120b451672

## Manual

If you cannot access to localhost, instead open the following URL:

https://keycloak.example.com/auth/realms/hello/protocol/openid-connect/auth?client_id=kubernetes&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code&scope=openid+email&state=********

Enter the code:

But i don't know how to use the manual mode.

Thanks for your help.

**Comment by int128** [comment]
The manual mode feature is no longer supported. It may be valuable in this case and will be added in the future.

**Comment by int128** [comment]
I just released v1.15.0 with this feature.
