### ISSUE TITLE
Add an option to not log validation token message

### ISSUE THREAD

**Issue by JrCs** [int128/kubelogin#164]
Hi,
i'm using kubelogin in credential mode.  
The problem i have is that kubelogin log message like `You got a valid token until 2019-10-18 08:53:54 +0200 CEST` in the terminal when it renew token.  

When using tools like [k9s](https://github.com/derailed/k9s) i see this messages all around the screen when kubelogin renew the tokens.  
![Capture](https://user-images.githubusercontent.com/83008/67074087-b2419700-f188-11e9-9b37-a84c03b912ee.PNG)

Can you add an option to not display this messages in the terminal ?

**Comment by int128** [comment]
Thank you for your contribution! I will release the new version soon.

**Comment by JrCs** [comment]
Thanks for the "patch" !
