### ISSUE TITLE
Why is the binary build with dynamically linked libs?

### ISSUE THREAD

**Issue by stvnwrgs** [int128/kubelogin#197]
I tried to install kubelogin in a alpine container. Executing it, I got the following error message:

```
bash-4.4# ./kubelogin
bash: ./kubelogin: No such file or directory
```

After checking with the file, I saw the binary is dynamically linked.

```
kubelogin: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, Go BuildID=htofILV-vmJ6aM3LQy_v/Ide4ML3en_nU-lVcMtst/-znD5V2I31dd2F6cMihW/8eEkgNdLqlPCpCXxJxR9, not stripped

bash-4.4# ldd kubelogin
	/lib64/ld-linux-x86-64.so.2 (0x7f7a1da77000)
	libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7f7a1da77000)
	libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f7a1da77000)

bash-4.4# ls /lib64/ld-linux-x86-64.so.2
ls: /lib64/ld-linux-x86-64.so.2: No such file or directory
```

Is the binary not build statically because it is a plugin for kubectl? If so, is it possible to build it without `/lib64/ld-linux-x86-64.so.2` ?
 

Quickfix for alpine: install `apk add libc6-compat`

**Comment by int128** [comment]
Would you check the new release?
https://github.com/int128/kubelogin/releases/tag/v1.15.2
