### ISSUE TITLE
renewal of id_token

### ISSUE THREAD

**Issue by binboum** [int128/kubelogin#207]
Hello all,

Thank you for the time you will take to answer me.

I have a question regarding renewal of id_token.

In my infrastructure, it is renewed every 3 minutes.

When I use the tool, a new page runs out, and refreshes the token automatically.

Is it possible to renew the token silently (without opening a web page) ?

It is possible to perform the operation with a curl on my side, I did not find in the documentation any information on this specific subject.

Thank you in advance.

**Comment by int128** [comment]
kubelogin will renew the ID token using the refresh token. If your identity provider supports the refresh token, it is possible to renew silently. You can see the logs by passing `-v1` option.

**Comment by binboum** [comment]
Thank you for your help, it was my provider which was not compatible, it's OK now.
