### ISSUE TITLE
2nd step (Verify authentication) fails, not able to launch browser 

### ISSUE THREAD

**Issue by jkr0103** [int128/kubelogin#213]
2nd step "Verify Authentication failes with below error":

Open http://localhost:8000 for authentication
Running firefox as root in a regular user's session is not supported. ($XAUTHORITY is /run/user/1000/gdm/Xauthority which is owned by master.)

Command executed and output is as below:

root@k8s-master:/home/master# kubectl oidc-login setup   --oidc-issuer-url=https://inteljk01.okta.com   --oidc-client-id=0oazjigxxWiepwhAc4x5   --oidc-client-secret=<my secret key>
## 2. Verify authentication
Open http://localhost:8000 for authentication
Running Firefox as root in a regular user's session is not supported.  ($XAUTHORITY is /run/user/1000/gdm/Xauthority which is owned by master.)
[29212:29212:0121/092054.807726:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
Running Firefox as root in a regular user's session is not supported.  ($XAUTHORITY is /run/user/1000/gdm/Xauthority which is owned by master.)
/usr/bin/xdg-open: 870: iceweasel: not found
/usr/bin/xdg-open: 870: seamonkey: not found
/usr/bin/xdg-open: 870: mozilla: not found
/usr/bin/xdg-open: 870: epiphany: not found
/usr/bin/xdg-open: 870: konqueror: not found
/usr/bin/xdg-open: 870: chromium: not found
/usr/bin/xdg-open: 870: chromium-browser: not found
[29242:29242:0121/092054.880173:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
/usr/bin/xdg-open: 870: www-browser: not found
/usr/bin/xdg-open: 870: links2: not found
/usr/bin/xdg-open: 870: elinks: not found
/usr/bin/xdg-open: 870: links: not found
/usr/bin/xdg-open: 870: lynx: not found
/usr/bin/xdg-open: 870: w3m: not found
xdg-open: no method available for opening 'http://localhost:8000'

**Comment by int128** [comment]
Would you try running with `--skip-open-browser` option?
