### ISSUE TITLE
Handle multiple `aud` claims

### ISSUE THREAD

**Issue by mrwulf** [int128/kubelogin#238]
Loading the jwt from disk fails because our oidc provides multiple audiences.

## Here is the failure messages:
```
error: error: could not get a token from the cache or provider: error while authentication: invalid token and you need to remove the cache: could not decode the json of token: json: cannot unmarshal array into Go struct field StandardClaims.aud of type string
```

## Here is an example of the token payload:
```
{
  "iss": "https://dex.example.com:5556/dex",
  "sub": "CgVid3VsZhIEbGrHcA",
  "aud": [
    "kube-web-auth",
    "kubelogin"
  ],
  "exp": 1581730258,
  "iat": 1581643858,
  "azp": "kubelogin",
  "nonce": "BHDpk6TlAb_LKA2AAdTCQLX28P2q57Rt4KrgW7u6ydY",
  "at_hash": "mv_5NjFLnLHwIK2B0wx0YQ",
  "groups": [
    "kubernetes-admins",
    "kubernetes-devs"
  ]
}
```

It looks like https://github.com/dgrijalva/jwt-go/issues/348 tracks this issue in the library project. There is a pre-release version that would probably work...

**Comment by int128** [comment]
Kubelogin uses only `exp` (checking expiration) and `sub` (showing the setup instruction) claims, and may work without jwt-go. I will try fix.

**Comment by int128** [comment]
FYI, RFC7519 says,
> In the general case, the "aud" value is an array of case-sensitive strings, each containing a StringOrURI value.  In the special case when the JWT has one audience, the "aud" value MAY be a single case-sensitive string containing a StringOrURI value.
>
> https://tools.ietf.org/html/rfc7519#section-4.1.3

**Comment by mrwulf** [comment]
Excellent - works like a charm! Do you have an ETA for the next release?

**Comment by int128** [comment]
I will release this today.
