### ISSUE TITLE
failed to verify id token signature

### ISSUE THREAD

**Issue by stokbaek** [int128/kubelogin#248]
Trying to get oidc and kubelogin to work with our own company oidc provider but I am getting the following error: 
`error: setup: authentication error: authentication error: authorization code flow error: could not verify the ID token: failed to verify signature: failed to verify id token signature`

I have taken all the ouput if I add `--v=9` to the command and https://jwt.io/ says token is vertified

**Comment by int128** [comment]
It seems the following line caused the error.
https://github.com/coreos/go-oidc/blob/8d771559cf6e5111c9b9159810d0e4538e7cdc82/jwks.go#L125-L125

coreos/go-oidc internally uses square/go-jose. Make sure [square/go-jose](https://github.com/square/go-jose) supports the algorithm of your oidc provider.

Unfortunately both do not provide any logs and it is very difficult to debug.

**Comment by stokbaek** [comment]
I have tried with both `{"alg":"ES256","crv":"P-256",`and `{"alg":"RS256","e":"AQAB"`

Both should be supported and both fails with the same error. They both work in jwt.io

**Comment by stokbaek** [comment]
Found the error, it requires key to be returned as a set
