### ISSUE TITLE
"no such host" error when multiple resolves exist on mac os.

### ISSUE THREAD

**Issue by LeoQuote** [int128/kubelogin#249]
kubelogin version: 1.17.1

![err](https://user-images.githubusercontent.com/4143818/75851006-93842a00-5e23-11ea-84c9-ef4bccdd3584.png)

In my case I'm connected to my enterprise with OpenVPN, which lead to multiple resolve address, it seems the dns resolve would fail at first one and wont retry with other resolves.

could be related to : 
* https://golang.org/pkg/net/#hdr-Name_Resolution
* https://github.com/golang/go/issues/15434

**Comment by mleklund** [comment]
I just opened #281 for the same reason.  If you compile from source you do not have this issue, it is because they are setting `CGO_ENABLED=0` when building the releases.

**Comment by int128** [comment]
This should be fixed in v1.19.2.
