### ISSUE TITLE
Is there any way to avoid distribution of ClientSecret to every enterprise user?

### ISSUE THREAD

**Issue by lalithvaka** [int128/kubelogin#279]
While exploring kubelogin use for enterprises, am not sure how practical and secure it is to distribute the client secret(via kubeconfig) to every user in an enterprise / teams? Wondering if there are alternates to this approach?

**Comment by mleklund** [comment]
how do you distribute the kubernetes CA certificates?  They are just as big a problem, or do you set `--insecure-skip-tls-verify` for all the clients?  There are a few projects which hide .kube/config files behind oauth proxies.

**Comment by Nuru** [comment]
One alternative is to use "public" OIDC clients which do not require client secrets. My understanding is that public clients are secure as long as you limit the redirect URLs, and you can safely limit the redirect URLs to `localhost` and `urn:ietf:wg:oauth:2.0:oob`
