### ISSUE TITLE
you must be logged in to the server (Unauthorized)

### ISSUE THREAD

**Issue by lalithvaka** [int128/kubelogin#280]
➜ kubectl --user=oidc get nodes
error: You must be logged in to the server (Unauthorized)

After the set up is done and the first time OIDC login is completes, my browser launches and disappear and I keep seeing the above error. Not sure how to debug this issue.

K8S v 1.15.3
kubectl client - 1.18.2

**Comment by tkg61** [comment]
Do you mind sharing what you did to solve this issue? I am also running into it. Thanks!
