### ISSUE TITLE
kubelogin does not respect VPN dns on OSX

### ISSUE THREAD

**Issue by mleklund** [int128/kubelogin#281]
This is directly related to this:

https://github.com/int128/kubelogin/pull/198

Maybe the homebrew recipe can build and set CGO_ENABLED=1, or the darwin release not set CGO_ENABLED=0?

**Comment by int128** [comment]
All binaries are built with CGO_ENABLED=0.

**Comment by mleklund** [comment]
I see that, I was wondering if you would consider a homebrew recipe that does not set CGO_ENABLED=0, or exclude the darwin binaries in your build setup from setting CGO_ENABLED=0.  

When CGO_ENABLED=0 is set on OSX kubelogin will not work for VPN connections to clusters that have split DNS, because of how OSX handles dns servers.  Basically you will only get what can be resolved with the settings in your resolv.conf which is largely unused in OSX these days.

#249 is caused by this issue.

**Comment by int128** [comment]
Currently the binaries are built on CircleCI go environment and cross-build with CGO_ENABLED=1 is not possible.
It seems possible to build for macOS with CGO_ENABLED=1 using https://hub.docker.com/r/dockercore/golang-cross/ image. I will try it.

**Comment by int128** [comment]
I found GitHub Actions supports macOS build. I will try it.

**Comment by int128** [comment]
This should be fixed in v1.19.2.
