### ISSUE TITLE
Can't use kubelogin with Gitlab because of the `code_verifier` parameter

### ISSUE THREAD

**Issue by Place1** [int128/kubelogin#282]
Kubelogin is sending the `code_verifier` parameter which isn't supported on Gitlab.

Here's an issue on Gitlab's issue tracker: https://gitlab.com/gitlab-org/gitlab/-/issues/213643

Perhaps PKCE should not be used if the OIDC provider doesn't support it? I believe this can be determined at runtime via the discovery endpoint.

**Comment by int128** [comment]
It may possible to determine the provider supports PKCE by `code_challenge_methods_supported ` of the discovery document as [RFC8414](https://tools.ietf.org/html/rfc8414#section-2).

For example, [Google](https://accounts.google.com/.well-known/openid-configuration) returns the following discovery document:

```json
 "code_challenge_methods_supported": [
  "plain",
  "S256"
 ],
```

[GitLab](https://gitlab.com/.well-known/openid-configuration)'s discovery document does not contain `code_challenge_methods_supported`.

**Comment by int128** [comment]
Would you check the new release v1.19.1? Thank you for your contribution.
