### ISSUE TITLE
Option for HTTPS redirect URL

### ISSUE THREAD

**Issue by dieterdemeyer** [int128/kubelogin#297]
Hello,

Would it be possible to add a feature so that HTTPS can be used for the redirect URL ?
I've been going through the code but I'm unable to find where the server is being started and if this option would be feasible or not...

Thanks in advance.

Regards.

**Comment by dieterdemeyer** [comment]
I've created a PR to enable this feature. Let me know if something is missing.

**Comment by int128** [comment]
Would you tell me why you need https for the local server? Does your identity provider require https redirect URI?

**Comment by dieterdemeyer** [comment]
Hi, yes, we have set up a keycloak instance which always requires https uris.

**Comment by dieterdemeyer** [comment]
@int128 , do you consider running the local server on https to be problematic ?

**Comment by int128** [comment]
I think Keycloak works even if the redirect URI is http. Is https for some security policy of your company?
If the local server runs on https, you need to add the CA certificate to the browser.

**Comment by dieterdemeyer** [comment]
Keycloak does indeed work for http redirects.
The redirect was failing due to a setting in the nginx configuration for the URL at which we expose Keycloak.

Now, it's working with the default settings so if you rather don't want to merge this request, feel free to close and decline the PR.

**Comment by int128** [comment]
I think the local server works well on HTTP in most cases and we do not need HTTPS for now.

- Pros
  - ?
- Cons
  - User needs to generate a TLS certificate.
  - User needs to add the certificate to the trust store to fix the browser warning.

Please let me know if you have any idea.
Thank you for your contribution!

**Comment by benoitentzmann** [comment]
Hello,
It seems that https is still not supported. I'm trying to connect to Azure which only support https for non localhost redirect uri:
https://learn.microsoft.com/en-us/azure/active-directory/develop/reply-url

The connection is working fine using http://localhost:8000 but we need to put instead the hostname of the server. But if I do so, I need to use https as this is the only option in Azure for Redirect URI.

Does the support of https still considered? Did somebody successfully tested authentication with Azure with anything else than localhost as redirect URI?

Many thanks in advance for your lights on this.
