### ISSUE TITLE
Improve instructions for install via Github Releases

### ISSUE THREAD

**Issue by lindhe** [int128/kubelogin#301]
Hi. Thanks for maintaining `kubelogin`, I find it very useful.

But something that is not very helpful is the current installation guide. It says:
```shell
curl -LO https://github.com/int128/kubelogin/releases/download/v1.19.1/kubelogin_linux_amd64.zip
unzip kubelogin_linux_amd64.zip
ln -s kubelogin kubectl-oidc_login
```

But this just downloads and links into `CWD` (wherever that happens to be when the user runs the commands), which makes little sense. Would be very helpful with instructions on where to put this binary and/or its symlink.

**Comment by int128** [comment]
Thank you for your comment!
It is recommended to use a package manager such as Homebrew or Krew for continuous updating. I think it would be better to remove GitHub Releases installation and add recommendation of package managers.

**Comment by lindhe** [comment]
Sounds like a good plan. It was fairly easy (for me, at least) to install it using krew, and having no further instructions would be better than confusing ones.

**Comment by yamlCase** [comment]
a lot of us are on rpm based machines and need the manual installation instructions.  Thanks!
