### ISSUE TITLE
Kubelogin with proxy

### ISSUE THREAD

**Issue by lanoxx** [int128/kubelogin#31]
Does kubelogin respect proxy settings set via `HTTPS_PROXY` or `HTTP_PROXY`?

**Comment by Baykonur** [comment]
It seems not, although I know GO respects HTTP_PROXY, HTTPS_PROXY and NO_PROXY but kubelogin does not seem to work on our environment where we have to set those environmental variables.

**Comment by Baykonur** [comment]
Dear @int128 
Do you have a release date? We are looking forward to this proxy support.

**Comment by int128** [comment]
Okay, I will release the next version tomorrow.

**Comment by int128** [comment]
I have released v1.9.0. Please let me know if you encounter any issue.

**Comment by lanoxx** [comment]
Thanks for working on this.

I am not sure this solution will work on windows if the proxy is set via PAC script. Did you take a look at the go-ieproxy library? That makes proxy support easiert.

**Comment by Baykonur** [comment]
No it will not as the code only checks for `HTTPS_PROXY` environmental variable. I suggest you to set it before executing `kubelogin` like; `set HTTPS_PROXY="http://blabla.com:8080"` 
Maybe create a `.bat` file. Within our environment (where the users have Windows workstations), this solution works.
If that does not help, maybe create another ticket and ask support for that specific `PROXY` setting?

**Comment by int128** [comment]
It seems kubectl does not support a PAC script so kubelogin does not support it for now.
