### ISSUE TITLE
Feature suggestion: Daemon mode + multi kluster

### ISSUE THREAD

**Issue by henricook** [int128/kubelogin#33]
I pretty much run klogin in a for loop all the time, because we have short access key life times (30 minutes) and I don't want to see 'you must login again' messages all the time

A daemon mode that does this automatically would be super cool. e.g. klogin -d -period=20m (daemon mode, refresh every 20 minutes)

For super bonus points if it could be logging me into a few clusters at the same time (-c "kluster1,kluster2,kluster3") that'd be awesome, so that i don't have to klogin again when i switch

**Comment by int128** [comment]
Now we can use the credential plugin and we don't need to refresh a token. Close.
