### ISSUE TITLE
Consider distributing via Krew

### ISSUE THREAD

**Issue by luisdavim** [int128/kubelogin#34]
Hi, it would be cool if kubelogin was available to install via Krew (https://github.com/GoogleContainerTools/krew).

**Comment by int128** [comment]
Thank you for your suggestion.
The krew yaml is available since v1.9.0.
I will submit it to the krew-index later.

**Comment by int128** [comment]
PR in progress: https://github.com/kubernetes-sigs/krew-index/pull/134

**Comment by int128** [comment]
Now `oidc-login` is available on krew-index.
Changed README.md as 40ef2c25b811ea42f16ff771fa61e46e3704e343
