### ISSUE TITLE
Skip login if current credentials are valid

### ISSUE THREAD

**Issue by sstarcher** [int128/kubelogin#35]
I want to have a flow where I have a alias that switches my context and does a login to assure my credentials are correct, but I also don't want it to do anything if my credentials are already valid.

I wrote this for Okta and it essentially does the same thing, but your tool is a kubectl plugin and works better in general.  https://github.com/sstarcher/k8s-auth

I would be willing to put in a PR for this feature if you will accept it.

**Comment by fishpen0** [comment]
I was also working on an alias that works this way and was struggling to find an easy way to tell if the current session is still valid, if kubelogin did that for me, it would make my life less complicated.

**Comment by sstarcher** [comment]
In the other project  I essentially did it by writing out a cache file, but a timestamp could probably  be tossed in the kubernetes yaml also.  https://github.com/sstarcher/k8s-auth/blob/master/main.go#L298

**Comment by int128** [comment]
Thank you for your suggestion.
I think we can check expiration by `exp` field of the ID token in the kubeconfig file.
