### ISSUE TITLE
added chocolatey package

### ISSUE THREAD

**Issue by jetersen** [int128/kubelogin#365]
A heads up as I have created a PR for chocolatey automatic update package.

Hopefully soon on Windows you would be able to run `choco install kubelogin`

https://github.com/chocolatey-community/chocolatey-coreteampackages/pull/1523

**Comment by jetersen** [comment]
Chocolatey package alive: https://chocolatey.org/packages/kubelogin

**Comment by jetersen** [comment]
@int128 the package is now approved.

Perhaps worth adding it to the readme?
`choco install kubelogin` :)

**Comment by int128** [comment]
Thank you for adding the package. 🎉 
I will add it to README.
