### ISSUE TITLE
Lens does not work with the credential plugin

### ISSUE THREAD

**Issue by int128** [int128/kubelogin#378]
**Describe the bug**
>@jetersen: https://github.com/int128/kubelogin/pull/341#issuecomment-680863401
>Tools like https://github.com/lensapp/lens does not work with kube credential plugin.
>The reason it does not work with credential plugin is because lens uses an embedded kubectl that is not aware of any installed krew plugins.

**To Reproduce**
TODO

**Expected behavior**
Lens works with the credential plugin.

**Environment**
 - OS: [e.g. macOS, Linux]
 - kubelogin version: [e.g. 1.19.3]
 - kubectl version: [e.g. 1.19]
 - OpenID Connect provider: [e.g. Google, Okta]

**Comment by jetersen** [comment]
Seems the new version of lens app mention they improved the support: https://github.com/lensapp/lens/releases/tag/v3.6.0

**Comment by jetersen** [comment]
I can confirm that lensapp v3.6.0 works well with krew plugins :) I just configured it and tested on Windows.
