### ISSUE TITLE
Success screen improvements

### ISSUE THREAD

**Issue by TJM** [int128/kubelogin#392]
## Purpose of the feature (why)
After successfully logging in, the tiny little "OK" in the top right corner of the browser is not a very good user experience, I propose that a message be centered on the screen, explain that the authentication was successful and what to do next, maybe even have a graphic.

## Your idea (how)
I saw one that seemed nicer when I logged in with Google Chat application which also uses OIDC auth/e

Here is what Google Chat's success screen looks like:
![Screen Shot 2020-09-30 at 6 04 47 PM](https://user-images.githubusercontent.com/1641316/94757966-1ab56400-0359-11eb-9793-46ce58ca985c.png)

vs:
![Screen Shot 2020-09-30 at 6 05 17 PM](https://user-images.githubusercontent.com/1641316/94757980-23a63580-0359-11eb-9b8e-46ff6ca59bb0.png)

**Comment by int128** [comment]
Thank you for your suggestion. The success screen has been updated in v1.19.3.
https://github.com/int128/kubelogin/releases/tag/v1.19.3

Feel free to propose a new screen if you have any idea.

**Comment by TJM** [comment]
Looks like a huge improvement! Apparently we are a bit behind on versions. I will instruct my teams to update to at least 1.19.3.

Thanks!
