### ISSUE TITLE
local error: tls: no renegotiation

### ISSUE THREAD

**Issue by kkeranov** [int128/kubelogin#408]
## Purpose of the feature (why)
When trying to login to an OIDC tenant with 'tls renegotiаtion' enabled the client cannot receive the token on successful OIDC login in browser. The execution of a kubectl command requiring oidc authentication fails with the following after successful oidc login in browser:
...
error: get-token: could not get a token: authentication error: authentication error: authorization code flow error: oauth2 error: could not exchange the code and token: Post "https://<oidc_url>/oauth2/token": local error: tls: no renegotiation

Stacktrace:
I1016 10:00:55.118440    1057 cmd.go:64] stacktrace: get-token:
    github.com/int128/kubelogin/pkg/adaptors/cmd.(*GetToken).New.func2
        /Users/distiller/project/pkg/adaptors/cmd/get_token.go:76
  - could not get a token:
    github.com/int128/kubelogin/pkg/usecases/credentialplugin.(*GetToken).Do
        /Users/distiller/project/pkg/usecases/credentialplugin/get_token.go:54
  - authentication error:
    github.com/int128/kubelogin/pkg/usecases/credentialplugin.(*GetToken).getTokenFromCacheOrProvider
        /Users/distiller/project/pkg/usecases/credentialplugin/get_token.go:102
  - authentication error:
    github.com/int128/kubelogin/pkg/usecases/authentication.(*AuthCode).Do
        /Users/distiller/project/pkg/usecases/authentication/authcode_browser.go:85
  - authorization code flow error:
    github.com/int128/kubelogin/pkg/usecases/authentication.(*AuthCode).Do.func2
        /Users/distiller/project/pkg/usecases/authentication/authcode_browser.go:74
  - oauth2 error:
    github.com/int128/kubelogin/pkg/adaptors/oidcclient.(*client).GetTokenByAuthCode
        /Users/distiller/project/pkg/adaptors/oidcclient/oidcclient.go:94
  - could not exchange the code and token: Post "https://<oidc_url>/oauth2/token": local error: tls: no renegotiation

kubelogin version: 1.19.4

## Your idea (how)
Enable support of tls renegotiation in kubelogin

**Comment by int128** [comment]
I will add a flag to enable TLS renegotiation. See https://github.com/int128/kubelogin/pull/401.
