### ISSUE TITLE
kubelogin freezes on startup on Windows

### ISSUE THREAD

**Issue by crazyjurich** [int128/kubelogin#436]
## Describe the issue
kubelogin takes very long to start on Windows.

    $ time kubelogin.exe --version
    kubelogin version v1.22.0

    real    0m43.708s
    user    0m0.000s
    sys     0m0.031s

I investigated the issue and found that freeze happens on __k8s.io/klog__ import.
Issue can be fixed by replacing k8s.io/klog with k8s.io/klog/v2, with minimal changes to code, see patch.

    $ time ./kubelogin.exe --version
    kubelogin version HEAD
    
    real    0m0.441s
    user    0m0.000s
    sys     0m0.015s

The problem is that V2 requires GO 1.13 when kubelogin is currently on 1.12. But it looks like 1.12 is out of support already.

Can we switch to 1.13? Please help.

[patch.txt](https://github.com/int128/kubelogin/files/5641447/patch.txt)

**Comment by int128** [comment]
Thank you for your investigation!

kubelogin is built with Go 1.15 and it's ready to merge your patch. Could you send me a pull request?

**Comment by crazyjurich** [comment]
Thank you, created a pull request https://github.com/int128/kubelogin/pull/439
