### ISSUE TITLE
Feature request: enforce PKCE

### ISSUE THREAD

**Issue by permis-b** [int128/kubelogin#440]
Microsoft Azure Active Directory does support authorization code flow with proof key for code exchange, see https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow, but the published metadata at the well-known URL does not contain the key `code_challenge_methods_supported` yet so kubelogin thinks that PKCE is not possible.

I would like a means to tell kubelogin to try PKCE anyway, maybe something like `--grant-type authcode-pkce`.

Many thanks in advance and keep up the excellent work.

**Comment by fl-max** [comment]
@permis-b were you able to find a workaround?

I cannot seem to get this to work with Azure but I don't see any reason why it shouldn't work.

**Comment by int128** [comment]
Is this issue still occurring?

It seems https://login.microsoftonline.com/common/.well-known/openid-configuration does not contain `code_challenge_methods_supported`.

**Comment by permis-b** [comment]
Unfortunately the issue persists. Microsoft still has to fix their JSON to match <https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow#request-an-authorization-code>.

**Comment by int128** [comment]
#599 is available in the latest release v1.24.0.
