### ISSUE TITLE
user specific access docs?

### ISSUE THREAD

**Issue by KlavsKlavsen** [int128/kubelogin#467]
How do you decide WHICH users, can access what?

does this create a unique role for each user (I'd assume so).. and then you can do rolebinding's to limit the access the "oicd userid" has ?

**Comment by KlavsKlavsen** [comment]
Here's an example of doing it for keycloak.. https://github.com/int128/kubelogin/issues/266
Does this look the same for Google OIDC ? 
That should be added to docs, to show how to manage access for each user.. 
The setup docs state to run:
```
kubectl create clusterrolebinding oidc-cluster-admin --clusterrole=cluster-admin --user='ISSUER_URL#YOUR_SUBJECT'
```
but what is YOUR_SUBJECT - for Google OIDC ? I hope its the individual users name - meaning i ONLY grant acccess to MY user - even though I may share the client secret (via kubeconfig) with everyone in my org ?

I'll gladly do a PR for your docs to explain this better for Google OIDC

**Comment by int128** [comment]
You can get your subject using `setup` subcommand:

```console
% kubectl oidc-login setup --oidc-issuer-url https://accounts.google.com --oidc-client-id REDACTED --oidc-client-secret REDACTED
...
You got a token with the following claims:

{
  "sub": "********",
  "iss": "https://accounts.google.com",
  "aud": "********",
  ...
}
```

The value of `sub` is your subject. Typically subject is just an identifier, not human readable.

If you need `email` based access control, set `--oidc-username-claim=email` to kube-apiserver and specify an email in a cluster role binding. See also the following config in the automated system test:

https://github.com/int128/kubelogin/blob/44ffd69cbf0ee9c11818e500552298a32d088ef0/system_test/cluster/cluster.yaml#L10-L14

https://github.com/int128/kubelogin/blob/44ffd69cbf0ee9c11818e500552298a32d088ef0/system_test/cluster/Makefile#L19

**Comment by KlavsKlavsen** [comment]
Thank you very much.. I'll try this with group based access control (as that's what I'd prefer) :) - or I might end up using keycloak with this instead.. I'll be sure to drop a PR with improved docs on whatever I have to dig up to get it working :)
