### ISSUE TITLE
"~/.kube/cache/oidc-login" on Windows is not the user home directory but a literal "~" directory in user home

### ISSUE THREAD

**Issue by LulaSvob** [int128/kubelogin#543]
## Describe the issue
Cache on Windows is in a folder called "~" inside the user directory. I.e. `C:\Users\<User.Name>\~\.kube`

## To reproduce
On Widows go to `C:\Users\<User.Name>\~\.kube`

## Your environment
- OS: Windows 10
- kubelogin version: kubelogin version v1.23.1 (go1.16.3 windows_amd64)
- kubectl version: v1.20.4
- OpenID Connect provider: Key Cloak

**Comment by trexx** [comment]
This seems to be a result of this change where previously a library detected the home directory, now the tilde is hardcoded and breaks on Windows.
https://github.com/int128/kubelogin/pull/489/files

**Comment by int128** [comment]
Thank you for bringing up this issue. I will fix this soon.
