### ISSUE TITLE
Configurable command to open a browser window

### ISSUE THREAD

**Issue by gvolpe** [int128/kubelogin#596]
## Purpose of the feature (why)

When running multiple instances of the same browser with different profiles, the command will rely on the `xdg-open` command (or equivalent) to open the browser, and this is problematic because it cannot be easily customized per terminal session.

E.g., I want to login via `kubectl` in my `work` profile but instead I'm taken to my `default` profile, which I used for personal stuff.

For now, I'm circumventing this issue via `--skip-open-browser`, copy the URL and manually open it in the right browser profile. 

## Your idea (how)

Would it be possible for `oidc-login` to add a `--browser-exec` option (or similar) to dictate how a browser should be open instead of relying on the shenanigans of the OS? Setting the `BROWSER` environment variable to a function that runs `firefox -p "work" -new-tab $1` doesn't seem to work.

I raised a similar issue in [pomerium](https://github.com/pomerium/pomerium/issues/2239), which is the mechanism we are currently using at work, but it never worked for me so we're evaluating alternatives.

Appreciate your time and consideration.

**Comment by int128** [comment]
How about writing a script to run the browser and setting it to `BROWSER` environment variable?

**Comment by gvolpe** [comment]
I was hoping it could be directly supported by `kubelogin`, instead of relying on the shenanigans of every supported OS, which is not reproducible. In my case (Linux), it relies on the behaviour of `xdg-open`, not on the `BROWSER` variable.

**Comment by int128** [comment]
Currently kubelogin uses https://pkg.go.dev/github.com/pkg/browser and it depends on:

- `open` in Darwin
- `xdg-open`, `x-www-browser` or `www-browser` in Linux
- `xdg-open` in FreeBSD and OpenBSD
- `ShellExecute` in Windows

It is possible to run the command instead if `BROWSER` environment variable is set. I will implement it.

**Comment by int128** [comment]
Finally I decided to add a flag for backward compatibility.

**Comment by gvolpe** [comment]
Thanks a lot @int128 , very much appreciated 🙏🏽

**Comment by int128** [comment]
Would you try the new release?

**Comment by gvolpe** [comment]
I just tried it out, it works like a charm, you're the best, thank you! 🤩
