### ISSUE TITLE
Feature request: Open browser automatically

### ISSUE THREAD

**Issue by henricook** [int128/kubelogin#7]
Hi all,

Love the script, it'd be great if it could (optionally) open the browser automatically, with bonus points for closing it automatically as well - that'd make my login process really slick!

**Comment by int128** [comment]
Thank you for the feature request.
I've released the new version and would you try it?

**Comment by henricook** [comment]
Amazing! Such a fast response, thanks - i'll try it out tomorrow

**Comment by henricook** [comment]
Sadly this didn't work for me, i type 'kubelogin' and I do see a tab appear and disappear very quickly in Chrome, but the CLI doesn't appear to detect it. 

Update: It detected it once but the majority of the time does not - i think it's *just* too early, maybe a slight delay before opening the browser? 200ms? 500ms? Something like that

**Comment by int128** [comment]
Would you check the new version?
https://github.com/int128/kubelogin/releases/tag/1.4.1

**Comment by henricook** [comment]
Thanks again, I managed to forget to check today, will report back on Monday

**Comment by henricook** [comment]
Sorry for the delay! I've tried with v1.5 and it's slightly better, now and then i still see the tab open and close but the CLI doesn't see it's been opened. But i'd say 50% of the time it works :+1:
