### ISSUE TITLE
Need an option to login without browser, only cli

### ISSUE THREAD

**Issue by evgenyidf** [int128/kubelogin#72]
While running LDAP login with integrated DEX, it is possible to insert user and password only in the browser. Using a cli only method will be very usefull.

**Comment by evgenyidf** [comment]
While running LDAP login with integrated DEX, it is possible to insert user and password only in the browser. Using a cli only method will be very usefull.

**Comment by int128** [comment]
#24.

**Comment by int128** [comment]
Thank you for the proposal. Would you try the new release?
