### ISSUE TITLE
M1 Apple Silicon, unable to install via brew

### ISSUE THREAD

**Issue by Thoro** [int128/kubelogin#737]
Hi,

I'm trying to install kubelogin via brew:

```
brew install int128/kubelogin/kubelogin
```

but it always loads the amd64 version, instead of the arm version:

```
==> Downloading https://github.com/int128/kubelogin/releases/download/v1.25.1/kubelogin_darwin_amd64.zip
```

Not sure where the error is, I guess the brew config is amiss somewhere?

**Comment by int128** [comment]
I added arm64 support in https://github.com/int128/homebrew-kubelogin/pull/43. Could you try again?

**Comment by Thoro** [comment]
Thanks, it works now!
