### ISSUE TITLE
arm64 build doesn't respect VPN on macos

### ISSUE THREAD

**Issue by mkmik** [int128/kubelogin#762]
## Describe the issue

This is the same issue as https://github.com/int128/kubelogin/issues/281  but re-appeared since kubelogin got released in a native arm64 binary (possibly because it's a cross compile?)

* works (under rosetta): https://github.com/int128/kubelogin/releases/download/v1.25.1/kubelogin_darwin_amd64.zip
* does not work: https://github.com/int128/kubelogin/releases/download/v1.25.1/kubelogin_darwin_arm64.zip

## To reproduce

```console
$ GODEBUG=netdns=1 kubelogin get-token --oidc-issuer-url  $ISSUER_URL --oidc-client-id=$CLIENT_ID
go package net: built with netgo build tag; using Go's DNS resolver
```

when using the GO DNS resolver kubelogin doesn't honour the system DNS settings used by the VPN tool to install the VPN private DNS server (in our case the VPN tool is `tailscale`, but I believe this applies to most VPN tools.)

## Your environment
- OS: macOS
- CPU: arm64
- kubelogin version: e.g. v1.25.1
- kubectl version: e.g. v1.24.1
- OpenID Connect provider: dex

**Comment by mkmik** [comment]
According to https://github.com/golang/go/issues/12524#issuecomment-1006174901 it may be possible to enable CGO also for cross builds for arm64 even when running on a macos CI worker on amd64

**Comment by int128** [comment]
Thank you for your contribution. I just released https://github.com/int128/kubelogin/releases/tag/v1.25.2.
