### ISSUE TITLE
Requesting groups from google

### ISSUE THREAD

**Issue by jadolg** [int128/kubelogin#958]
## Describe the question
Hi folks :wave: 
I'm trying to setup login with Google and so far I'm unable to get claims for groups.
Is there any step-by-step guide on how to achieve this?

## To reproduce
- Use the basic setup with Google credentials.
- The token you get in response has no `groups` claim.

## Your environment
- OS: Ubuntu
- kubelogin version: v1.28.0
- kubectl version: v1.27.3
- OpenID Connect provider: Google

**Comment by jeffmccune** [comment]
Google doesn't support the oidc groups claim at this time.  Consider using Dex to bridge the gap with the necessary groups API call.

**Comment by jadolg** [comment]
That's what I ended up doing. Thanks for your answer.
