### ISSUE TITLE
Issue after upgrade to 1.28.0

### ISSUE THREAD

**Issue by daveschmidt86** [int128/kubelogin#960]
## Describe the issue
After upgrading to 1.28.0 I am no longer redirected to my OIDC provider and instead redirected to http://localhost/ in my browser. No changes to my kube config file, works with version 1.27. I didn't see anything in release notes that points to why, curious if anyone else had this issue as well?

## To reproduce
kubectl get pods -v9

Result in terminal:
I0726 21:50:37.010199    4602 loader.go:373] Config loaded from file:  /Users/me/.kube/config
I0726 21:50:37.010710    4602 round_trippers.go:466] curl -v -XGET  -H "Accept: application/json;g=apidiscovery.k8s.io;v=v2beta1;as=APIGroupDiscoveryList,application/json" -H "User-Agent: kubectl/v1.27.3 (darwin/arm64) kubernetes/25b4e43" 'https://10.4.20.231:6443/api?timeout=32s'

browser redirects to https://localhost/

## Your environment
- MacOS 13.5
- kubelogin version: 1.28.0
- kubectl version: 1.27
- OpenID Connect provider: Keycloak

**Comment by miroslavhudak** [comment]
Same...How you fix this?

**Comment by daveschmidt86** [comment]
I cleared my browser cache in FireFox and it started working again.
